language: go
go:
- '1.12'
env:
- GO111MODULE=on
script:
- make test
notifications:
  slack:
    secure: uEyU0zFD/j6hKGyAvyvBiWHG8y1tI1qU9gQ4zYrYTb2O8bP7ArCo9FhXqBlE63H6Ol3TEEjg4DH2Hz3H3inQJMN7Xw63n3OC2gmMwezlpH1BodTP9WfxKmXzqucQOfjN9pXy6/c3Gi4j5yhdik7ww44AoKryTNRW/KtQ04a3NTpikwb1nIMpBM9MYslu+dxPl5V2nuzNklMOznqlvjOkW86xmYYP0lNQfQM4pb9nCsEJTyIHr6mXrLiAnBH7a2ez3tDeaNTjE0cb7q3FDF5/85xNNY7/zOg9oHA9DV7i40VgFRU1oDvPwj4jA53Z2EhfsCdG0RDEPlCFdHzemDXGo0Vm/D0RGYy80SrBbzvLy9H1qGEYkVC98SSDUZLxyAw+Qt8697vodpEKcrF5wx2Mg2uHlYs3EMPR0aZlm8iusELpTISgxNOhemFgBFUFiB0Fud7x1xQY08EYw7i4RpNe/9i6dSOkk8+s4TOkNGSLGtly65MtI37lspTVAf7GBA8z+DO95YCuhBBVokGlNVPogFUcxGvz+4BcTsxacs/yms3t2ZDVsiBClALfX9WMZNQbxF/IhcBAhyzwvpRfEvXuxmbjQMBKWAYS/0t16NitNuSsOAZ7x4shVh6zG9g0Qk/qZ6c28TtRlopevF0qt1OgZOZ8eyqjwVohRnavyiDc4qo=
